repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/psf/black
    rev: 26.3.1
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/docformatter
    rev: 06907d0267368b49b9180eed423fae5697c1e909
    hooks:
      - id: docformatter
        additional_dependencies: [tomli]
        args:
          - --close-quotes-on-newline
          - --make-summary-multi-line
          - --in-place
          - --black
          - --pre-summary-newline
          - --config
          - ./pyproject.toml

  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort

  - repo: https://github.com/PyCQA/flake8
    rev: 7.2.0
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        additional_dependencies: [types-pytz, types-requests]
        args: ["--config-file=mypy.ini"]
